{% set PYTHON_MIN = "3.9" %}
{% set VERSION = "2.0.0b0" %}
{% set SHA256 = "d37aeefbfafa8d85de8a1f324d8ae3f14e75b887e43136d70af665b754a038d6" %}
# curl -sL https://github.com/kreshuklab/plant-seg/archive/refs/tags/2.0.0a4.tar.gz | openssl sha256

package:
  name: plant-seg
  version: {{ VERSION }}

source:
  url: https://github.com/kreshuklab/plant-seg/archive/refs/tags/{{ VERSION }}.tar.gz
  sha256: {{ SHA256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-cache-dir
  number: 1
  entry_points:
    - plantseg = plantseg.run_plantseg:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools  # Added to specify the build backend

  run:
    - python >={{ python_min }}
    - pytorch >=1.7.0
    - tifffile
    - h5py
    - zarr
    - vigra
    - python-elf
    - python-graphviz
    - scikit-image
    - bioimageio.core >=0.6.5
    - napari
    - pyqt
    - requests
    - pyyaml
    - pydantic >2,<2.10

test:
  requires:
    - python {{ python_min }}
  imports:
    - plantseg

about:
  home: https://kreshuklab.github.io/plant-seg/
  summary: 'Cell instance segmentation in densely packed 3D volumetric images'
  description: |
    PlantSeg is a tool for cell instance aware segmentation in densely packed 3D volumetric images.
    The pipeline uses a two stage segmentation strategy (Neural Network + Graph Partitioning).
    The pipeline is tuned for plant cell tissue acquired with confocal and light sheet microscopy.
    Pre-trained models are provided.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://kreshuklab.github.io/plant-seg/
  dev_url: https://github.com/kreshuklab/plant-seg

extra:
  recipe-maintainers:
    - lorenzocerrone
    - wolny
    - qin-yu
