{% set version = "2.0.0-alpha" %}

package:
  name: plant-seg
  version: {{ version }}

source:
  url: https://github.com/kreshuklab/plant-seg/archive/refs/tags/{{ version }}.tar.gz
  sha256: 779c21a33311d8387f0f9c33e91cd9e559b1872713656c00308622e151f0c86d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-cache-dir
  number: 0
  entry_points:
    - plantseg = plantseg.run_plantseg:main

requirements:
  build:
    - python>=3.9
    - pip

  run:
    - python
    - pytorch
    - tifffile
    - h5py
    - zarr
    - vigra
    - python-elf
    - python-graphviz
    - scikit-image
    - bioimageio.core>=0.6.5
    - napari
    - requests
    - pyyaml
    - pydantic>2

test:
  imports:
    - plantseg
  requires:
    - pytest
  run:
    - pytest

about:
  home: https://kreshuklab.github.io/plant-seg/
  summary: 'Cell instance segmentation in densely packed 3D volumetric images'
  description: |
    PlantSeg is a tool for cell instance aware segmentation in densely packed 3D volumetric images.
    The pipeline uses a two stage segmentation strategy (Neural Network + Graph Partitioning).
    The pipeline is tuned for plant cell tissue acquired with confocal and light sheet microscopy.
    Pre-trained models are provided.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://kreshuklab.github.io/plant-seg/
  dev_url: https://github.com/kreshuklab/plant-seg

extra:
  recipe-maintainers:
    - lorenzocerrone
    - wolny
    - qin-yu
