{% set PYTHON_MIN = "3.11" %}
{% set VERSION = "2.0.0rc10" %}
{% set SHA256 = "ed620a8f853007fb61404d2e58cea53f3f2c06984c8a7faf7ad22b11beb46a29" %}
# curl -sL https://github.com/kreshuklab/plant-seg/archive/refs/tags/2.0.0rc1.tar.gz | openssl sha256

package:
  name: plant-seg
  version: {{ VERSION }}

source:
  url: https://github.com/kreshuklab/plant-seg/archive/refs/tags/{{ VERSION }}.tar.gz
  sha256: {{ SHA256 }}

build:
  noarch: python
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-cache-dir"
    - "mkdir -p {{ PREFIX }}/Menu"  # [not win]
    - "cp {{ SRC_DIR }}/Menu/plant-seg.json {{ PREFIX }}/Menu/{{ PKG_NAME }}_menu.json"  # [not win]
    - "cp {{ SRC_DIR }}/Menu/icon.png {{ PREFIX }}/Menu/icon.png"  # [not win]
    - "cp {{ SRC_DIR }}/Menu/icon.ico {{ PREFIX }}/Menu/icon.ico"  # [not win]
    - "cp {{ SRC_DIR }}/Menu/logo_horizontal.png {{ PREFIX }}/Menu/logo_horizontal.png"  # [not win]
    - "cp {{ SRC_DIR }}/Menu/logo_vertical.png {{ PREFIX }}/Menu/logo_vertical.png"  # [not win]

  entry_points:
    - plantseg = plantseg.run_plantseg:main

requirements:
  build:
    - python {{ PYTHON_MIN }}
    - pip
    - setuptools

  run:
    - python >={{ PYTHON_MIN }}
    - pip
    # Neural Network
    - pytorch<=2.9.1
    - tensorboard<=2.20.0
    # Bioimage and CV
    - tifffile<=2025.12.12
    - h5py<=3.151
    - zarr<=3.1.5
    - vigra<=1.12.2
    - python-elf<=0.7.3
    - python-graphviz<=0.21
    - scikit-image<=0.25.2
    - bioimageio.core<=0.9.5
    - bioimageio.spec<=0.5.6
    # GUI
    - qtpy<=2.4.3
    - pyside6<=6.10.1
    - napari<=0.6.6
    - qt-material<=2.14
    # Other
    - requests<=2.32.5
    - pyyaml<=6.0.3
    - pydantic<=2.11.10


test:
  requires:
    - python {{ PYTHON_MIN }}
  imports:
    - plantseg

about:
  home: https://kreshuklab.github.io/plant-seg/
  summary: 'Cell instance segmentation in densely packed 3D volumetric images'
  description: |
    PlantSeg is a tool for cell instance aware segmentation in densely packed 3D volumetric images.
    The pipeline uses a two stage segmentation strategy (Neural Network + Graph Partitioning).
    The pipeline is tuned for plant cell tissue acquired with confocal and light sheet microscopy.
    Pre-trained models are provided.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://kreshuklab.github.io/plant-seg/
  dev_url: https://github.com/kreshuklab/plant-seg

extra:
  recipe-maintainers:
    - KRiedmiller
    - lorenzocerrone
    - wolny
    - qin-yu
